// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Aside: typeof import('./src/components/Aside.vue')['default']
    BranchConfig: typeof import('./src/components/branch-config.vue')['default']
    Content: typeof import('./src/components/Content.vue')['default']
    CustomizeConfig: typeof import('./src/components/customize-config.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Instruction: typeof import('./src/components/instruction.vue')['default']
    ModalBox: typeof import('./src/components/ModalBox.vue')['default']
    ModalView: typeof import('./src/components/modal-view.vue')['default']
    ProjectUpdate: typeof import('./src/components/project-update.vue')['default']
    Release_list: typeof import('./src/components/release_list.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Versions: typeof import('./src/components/versions.vue')['default']
  }
}

export {}
